name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened            # opened
      - reopened          # reopened
      - synchronize       # new commit(s) pushed
      - ready_for_review  # for draft support

jobs:
  # TOOD: cleanup js codes
  # https://github.com/curvegrid/hackathon-sunset-supreme/issues/4
  # eslint:
  #   name: eslint
  #   if: |
  #     (github.event_name == 'push') ||
  #     (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
  #   runs-on: ubuntu-18.04
  #   timeout-minutes: 10
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Run Eslint
  #       run: |
  #         yarn install
  #         yarn lint
  tests:
    name: tests
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        env:
          CLASPRC_ACCESS_TOKEN: ${{ secrets.CLASPRC_ACCESS_TOKEN }}
          CLASPRC_REFRESH_TOKEN: ${{ secrets.CLASPRC_REFRESH_TOKEN }}
          CLASPRC_EXPIRY_DATE: ${{ secrets.CLASPRC_EXPIRY_DATE }}
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ACCESS_TOKEN: ${{ secrets.CLIENT_ACCESS_TOKEN }}
          CLIENT_REFRESH_TOKEN: ${{ secrets.CLIENT_REFRESH_TOKEN }}
          CLIENT_EXPIRY_DATE: ${{ secrets.CLIENT_EXPIRY_DATE }}
        run: |
          yarn global add @google/clasp
          yarn install
          export CLASPRC_ACCESS_TOKEN="$CLASPRC_ACCESS_TOKEN"
          export CLASPRC_REFRESH_TOKEN="$CLASPRC_REFRESH_TOKEN"
          export CLASPRC_EXPIRY_DATE="$CLASPRC_EXPIRY_DATE"
          export SCRIPT_ID="$SCRIPT_ID"
          export CLIENT_ID="$CLIENT_ID"
          export PROJECT_ID="$PROJECT_ID"
          export CLIENT_SECRET="$CLIENT_SECRET"
          export CLIENT_ACCESS_TOKEN="$CLIENT_ACCESS_TOKEN"
          export CLIENT_REFRESH_TOKEN="$CLIENT_REFRESH_TOKEN"
          export CLIENT_EXPIRY_DATE="$CLIENT_EXPIRY_DATE"
          node generateCredentials.js
          ls -l $HOME/.*.json
          ls .*.json
          PATH=$PATH:"$(yarn global bin)"
          clasp login --creds ~/.clasprc.json
          clasp push
          yarn test
